Vdg/footer testimonials
WildCodeSchool/2023-09-wns-rouge-renthub-front pull request #41
Opened 2024-05-13 21:40 UTC by victorDGW

2024-05-14 06:58 UTC, hugodavid1 approved these changes

2024-05-14 06:58 UTC, hugodavid1 commented on pnpm-lock.yaml
git ignore le pnpm.yaml stp ;)

2024-05-14 07:09 UTC, hugodavid1 requested changes

2024-05-14 07:09 UTC, hugodavid1 commented on src/components/cards/FooterMenuCard.tsx
pourquoi utiliser des Box puis juste en dessous des div ? Soit l'un soit à l'autre ?

2024-05-14 07:09 UTC, hugodavid1 commented on src/components/cards/TestimonialsCard.tsx
pareil sur ce fichier tu as div + Box

2024-05-14 07:09 UTC, hugodavid1 commented on src/components/home/Testimonials.tsx
> +      items: 3,
je pense qu'ici ça aurait été moins lourd d'utiliser les breakpoint mui au lieu d'avoir cette méga constante ?

2024-05-14 07:09 UTC, hugodavid1 commented on src/components/home/testimonials.scss
> +  }
je me demandais pourquoi faire tout les média query à la mano ? Pour être plus précis ?

2024-05-14 07:09 UTC, hugodavid1 commented on src/pages/_app.scss
> +body,
je me demandais à quoi ça sert toutes ces balises html ?

2024-05-14 07:33 UTC, victorDGW commented on src/components/home/Testimonials.tsx
> +      items: 3,
c'est une librairie externe qui gere ce composant carousel et non celui de miui. J'ai repris exactement ce qui avait été fait sur l'autre carousel et la doc

2024-05-14 07:41 UTC, victorDGW commented on src/pages/_app.scss
> +body,
Ce fichier "RESET CSS"  réinitialise  les styles par défaut des éléments HTML pour assurer une base cohérente et uniforme pour le style des pages web.
Il sert à éliminer les styles par défaut du navigateur afin que  tu puisses commencer à styliser vos pages web à partir d'une base propre et uniforme ( cas d'usage courant)

2024-05-14 07:45 UTC, victorDGW commented on src/components/home/testimonials.scss
> +  }
c'est une facon de faire parmis d'autre... on surchage le comportement du carousel ici. Si tu as une autre methode je suis preneur

2024-05-14 08:04 UTC, victorDGW commented on src/components/cards/FooterMenuCard.tsx
l'un n'empeche pas l'autre ??

2024-05-14 08:05 UTC, victorDGW commented on src/components/cards/TestimonialsCard.tsx
meme reponse que précédemment !

2024-05-14 09:30 UTC, Lukasz-Grzegorzewski approved these changes

2024-05-16 13:36 UTC, hugodavid1 approved these changes

2024-05-16 13:36 UTC, hugodavid1 commented on src/pages/_app.scss
> +body,
à priori MUI le fait nativement

2024-05-16 15:22 UTC, merged